# fly.toml file generated for dangra-hs57378 on 2023-03-31T12:46:51Z
app = "dangra-hs57378"
primary_region = "scl"

[[services]]
  internal_port = 80
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    timeout = "2s"

[checks.listen]
port = 80
type = "tcp"
grace_period = "1s"
interval = "15s"
timeout = "2s"
